---
title: "EX 02 - Data Handling & MLE"
author: "Afek Adler"
date: "`r Sys.Date()`"
output:
  html_document :  
    number_sections: TRUE
---
Last time it was an intro lecture. \\
In the Lecture you have seen point estimates - unbiased estimates and the bias-variance decomposition - 
\[ \operatorname{MSE}(\boldsymbol{\Theta})=E[\boldsymbol{\Theta}-E(\boldsymbol{\Theta})]^{2}+[\theta-E(\boldsymbol{\Theta})]^{2}\]
\[=V(\hat{\Theta})+(\text { bias })^{2}\]


## Revision - the normal distribution - 
\[f\left(x | \mu, \sigma^{2}\right)=\frac{1}{\sqrt{2 \pi \sigma^{2}}} e^{-\frac{(x-\mu)^{2}}{2 \sigma^{2}}}\]

### Expectency and Variance of the sample mean (i.i.d)
\[E(\bar{X})=E\left(\frac{1}{n} \sum_{i=1}^{n} X_{i}\right)=\frac{1}{n} \sum_{i=1}^{n} E\left(X_{i}\right)=\frac{1}{n} \sum_{i=1}^{n} \mu=\frac{1}{n} \cdot n \mu=\mu\]


\[V(\bar{X})=V\left(\frac{1}{n} \sum_{i=1}^{n} X_{i}\right)=\frac{1}{n^{2}} \sum_{i=1}^{n} V\left(X_{i}\right)=\frac{1}{n^{2}} \sum_{i=1}^{n} \sigma^{2}=\frac{1}{n^{2}} \cdot n \sigma^{2}=\frac{\sigma^{2}}{n}\]


The distribution of a sample (i.i.d) from the normal distribution (on board).

## Deriving an unbiased estimate for $\sigma^{2}(S^{2})$ - 

\[E\left(S^{2}\right)=E\left[\frac{\sum_{i=1}^{n}\left(X_{i}-\bar{X}\right)^{2}}{n-1}\right]=\frac{1}{n-1} E \sum_{i=1}^{n}\left(X_{i}-\bar{X}\right)^{2}\]

\[=\frac{1}{n-1} E \sum_{i=1}^{n}\left(X_{i}^{2}+\bar{X}^{2}-2 \bar{X} X_{i}\right)=\frac{1}{n-1} E\left(\sum_{i=1}^{n} X_{i}^{2}-n \bar{X}^{2}\right)\]

\[=\frac{1}{n-1}\left[\sum_{i=1}^{n} E\left(X_{i}^{2}\right)-n E\left(\bar{X}^{2}\right)\right]\]

Reacall that - $E\left(X_{i}^{2}\right)=\mu^{2}+\sigma^{2}$ and $\mu^{2}+\sigma^{2} / n$
So - 
\[E\left(S^{2}\right)=\frac{1}{n-1}\left[\sum_{i=1}^{n}\left(\mu^{2}+\sigma^{2}\right)-n\left(\mu^{2}+\sigma^{2} / n\right)\right]\]
\[=\frac{1}{n-1}\left(n \mu^{2}+n \sigma^{2}-n \mu^{2}-\sigma^{2}\right) = \sigma^{2} \]

# Central limit theoram 
Let there be n random variable such that - 
\[E(X_i) = \mu,V(X_i) = \sigma \]
Than, for a large n:
\[\sum_{n} X_{i} \sim N\left(n \mu, n \sigma^{2}\right)\]
\[\bar{X} \sim N\left(\mu, \frac{\sigma^{2}}{n}\right)\]
# example of a question with numbers (attached in word format)

