---
title: "EX 04 - confidense intervals and MLE motivation"
author: "Afek Adler"
date: "`r Sys.Date()`"
output:
  html_document :  
    number_sections: TRUE
---

Last excercise we did:

  * Cover methods for point estimation
  * Get to know dplyr package
  * Talked about what makes an estimator a good one

Today we will:

  * Explain again some terms (central limit theorem, what is an estimator, what is a moment)
  * Revise MLE with an example
  * Talk on interavel estimation


## What is an the difference between $\theta$ and $\hat{\theta}$
$\theta$ is the population parameter (we will never know it). 
$\hat{\theta}$ estimates $\theta$ based on a sample from the population. 

## What is a moment?
The moments of a function describes it's shape.
In the method of moments we assume that our sample is big enough such that the sample moments are approximately equal to the population moments. And that's how we estimate parameters.

## Central limit theoram
Q1 in excercise notes


# Another MLE and Moments example
Q2 in excercise notes


# Interval Estimation

## The student's t distribution 
t distribution is used to model the expected values of a **small** sample from a population that is distributed noraml with unknown variance.
As N increases, t distribution is getting closer and closer to the normal distribution.

Lemma: 
$\frac{\bar{X}-\mu}{S / \sqrt{n}}$ is t- distributed.

[Student t dist vs normal dist as function of n](https://rpsychologist.com/d3/tdist/)

## confidense interval

In statistics, a confidence interval (CL) is a type of interval estimate, computed from the statistics of the observed data, that might contain the true value of an unknown population parameter. The interval has an associated confidence level, or coverage that, loosely speaking, quantifies the level of confidence that the deterministic parameter is captured by the interval. More strictly speaking, the confidence level represents the frequency (i.e. the proportion) of possible confidence intervals that contain the true value of the unknown population parameter. **In other words, if confidence intervals are constructed using a given confidence level from an infinite number of independent sample statistics, the proportion of those intervals that contain the true value of the parameter will be equal to the confidence level**. [wiki](https://en.wikipedia.org/wiki/Confidence_interval)

There are one sided and two sided confidense intervals.

### confidense interval for the mean based on n samples: 
Based on our assumptions we get a different distribution of the sample, after we figure out how the sample is distributed computing the confidense interval is straighforward. for example, for the mean - 

\[\mu \in(\bar{X}-\#of\_std_\_for\_confidense\_level\_\alpha*std,\bar{X}+\#of\_std_\_for\_confidense\_level\_\alpha*std) \]
1.When variance is known and the population is assumed to be distributer notmal or n is "big" (n > 30), the sample mean is distributed
\[\mathcal{N}\left(\bar{X} , \frac{\sigma^{2}}{n}\right)\]
So  a two sided confidense interval is:
\[\mu \in\left(\bar{X}-Z_{1-\frac{\alpha}{2}} \frac{\sigma}{\sqrt{n}},\bar{X}+Z_{1-\frac{\alpha}{2}} \frac{\sigma}{\sqrt{n}}\right)\]
2 .When variance is **not** known and n is "big" (n > 30), the sample mean is distributed
\[\mathcal{N}\left(\bar{X} , \frac{\hat{\sigma}^{2}}{n}\right)\]
3. When variance is **not** known and n is **not** "big" (n <= 30), the sample mean is distributed
\[\mathcal{t_{n-1}}\left(\bar{X} , \frac{\hat{\sigma}^{2}}{n}\right)\] 

Reminder:
\[\hat{\sigma}^{2} = S^2 =\frac{\sum_{i=1}^{n}\left(X_{i}-\bar{X}\right)^{2}}{n-1}=\frac{\sum_{i=1}^{n} X_{i}^{2}-n \bar{X}^{2}}{n-1} \]

For your own understanding, for each case, derive the one sided and two sided confidense interval at home.

* We have seen in the lecture alse CL for the $\sigma^2$, and we will encounter it at HW2 as well.

### confidense interval for the proportion based on n samples
if n is large enough, the proportion is distributed:
\[\mathcal{N}\left(\hat{p} , \frac{\hat{p}\hat{q}}{n}\right)\]

**Q1:**
An online advertising company is doing an ab testing for a new advertisement and wants to model a confidense interval for the click thorogh rate (CTR) of a givent test such that it's confidense interval will be smaller than 5%  in confidense level of 95% . What is the minmum number of sample for this purpose?

\[0.05 = Length \geq 2*Z_{1-\frac{\alpha}{2}}*\sqrt{\frac{\hat{p}\hat{q}}{n}} =  2*Z_.975*\sqrt{\frac{\hat{p}\hat{q}}{n}} \Rightarrow\]
\[=  2*1.96*\sqrt{\frac{\hat{p}\hat{q}}{n}} \Rightarrow\ 0.01275 \geq \sqrt{\frac{\hat{p}\hat{q}}{n}} \Rightarrow\ n \geq \frac{\hat{p}\hat{q}}{0.00016} \Rightarrow\]
\[n \geq  \frac{\hat{p}\hat{q}}{0.00016} = \frac{0.5*0.5}{0.00016} = 1562.5\]
because \[ p(1-p) \leq 0.5*0.5  \ \forall p \in \{0,1\} \]

If we know for example that the CTR is bounded by 4% than:
\[n \geq  240 = \frac{0.04*0.96}{0.00016} \geq \frac{\hat{p}\hat{q}}{0.00016}\]

# CL Verification
Let's verify that indeed when we bouild CI (and..our assumptions are correct) than $1-\alpha$ our parameter is inside the CI:  
``` {r confidense interval}
miu = 10
sigma = 3
n = 10
alpha = 0.1
N_tests <- 10000
counter <- 0
error = qnorm(1-alpha/2)*(sigma/sqrt(n))
for (i in 1:N_tests)
  {sample = rnorm(n,miu,sigma)
  sample_mean <- mean(sample)
  left <- sample_mean-error 
  right <- sample_mean + error
  between <- (left <= miu) & (miu <= right)
  counter <- counter+between}
print(counter/N_tests)
```


