#
# A small shiny app which illustrates the normal distribution, 
# and the relationship between alpha, z, one sided and two sided intervals

library(shiny)
library(tidyverse)

source("plot_z_score.R")

z_dense <- tibble(z_range = seq(-3, 3, by = 0.025),
                  density = dnorm(z_range),
                  p_range = pnorm(z_range))

ui <- fluidPage(
    theme = shinythemes::shinytheme("united"), title = "Demonstrating the normal distribution",
    fluidRow(
        sidebarLayout(
            sidebarPanel(width = 3,
                         fluidRow(
                             h3("Input parameters"),
                             sliderInput("alpha", "α-level (alpha)", value = 0.05, 
                                         min = 0, max = 1, step = 0.025,
                                         animate = TRUE),
                             sliderInput("z", "z-score", value = qnorm(0.05),
                                         min = -3, max = 3, step = 0.05),
                             radioButtons("alternative", "Two- or one-sided test",
                                          choices = c("One sided" = "one.sided",
                                                      "Two sided" = "two.sided"),
                                          selected = "one.sided"
                                          )
                         )),
            mainPanel(
                h3("Illustration of the normal distribution"),
                plotOutput("z_plot"),
                fluidRow(
                    p("This app was generated by Adi Sarid, as a tool to demonstrate the relationship between the quantiles, the density, and the cumulative distribution function of a normal distribution. 
                         Change the controls on the right to see how it reflects on the chart."),
                    p("The source code for this app is available in the a github repository:",
                      a("https://github.com/adisarid/intro_statistics_R/tree/master/distribution_shiny_app", 
                        href = "https://github.com/adisarid/intro_statistics_R/tree/master/distribution_shiny_app", 
                        target = "_blank")),
                    p("The use of this tool is permitted via the cc-by-sa, with attribution to ", 
                      a("Adi Sarid", href = "https://adisarid.github.io", 
                        target = "_blank"))
                )
            )
        )
    )
)

# Define server logic required to draw a histogram
server <- function(input, output, session) {
    
    output$z_plot <- renderPlot({
        
        plot_z_score(p = input$alpha,
                     alternative = input$alternative,
                     z_dense)
    })
    
    observeEvent(input$alpha, {
        
        if (input$alternative == "one.sided"){
            updateSliderInput(session,
                              "z",
                              value = qnorm(p = input$alpha)
            )
        } else {
            updateSliderInput(session,
                              "z",
                              value = qnorm(p = input$alpha/2)
            )
        }
        
    })
    
    observeEvent(input$z, {
        if (input$alternative == "two.sided") {
            new_alpha <- pnorm(input$z)*2
        } else {
            new_alpha <- pnorm(input$z)
        }
        
        if (!near(new_alpha, input$alpha, tol = 0.01)) {
            updateSliderInput(session,
                              "alpha",
                              value = new_alpha)   
        }
    })
    
    observeEvent(input$alternative, {
        if (input$alternative == "two.sided"){
            updateSliderInput(session, 
                              "z",
                              min = -3, max = 0)
        } else {
            updateSliderInput(session,
                              "z",
                              min = -3, 
                              max = 3)
        }
    })

}

# Run the application 
shinyApp(ui = ui, server = server)
